//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteBibliotecaElSaber.ServidorElSaber {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBinding", Namespace="http://schemas.datacontract.org/2004/07/ElSaberServices.Contratos")]
    [System.SerializableAttribute()]
    public partial class UsuarioBinding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string puestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string puesto {
            get {
                return this.puestoField;
            }
            set {
                if ((object.ReferenceEquals(this.puestoField, value) != true)) {
                    this.puestoField = value;
                    this.RaisePropertyChanged("puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionBinding", Namespace="http://schemas.datacontract.org/2004/07/ElSaberServices.Contratos")]
    [System.SerializableAttribute()]
    public partial class DireccionBinding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDireccion {
            get {
                return this.IdDireccionField;
            }
            set {
                if ((this.IdDireccionField.Equals(value) != true)) {
                    this.IdDireccionField = value;
                    this.RaisePropertyChanged("IdDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                if ((object.ReferenceEquals(this.ciudadField, value) != true)) {
                    this.ciudadField = value;
                    this.RaisePropertyChanged("ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPostalField, value) != true)) {
                    this.codigoPostalField = value;
                    this.RaisePropertyChanged("codigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoBinding", Namespace="http://schemas.datacontract.org/2004/07/ElSaberServices.Contratos")]
    [System.SerializableAttribute()]
    public partial class AccesoBinding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteBibliotecaElSaber.ServidorElSaber.UsuarioBinding IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoDeUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAcceso {
            get {
                return this.IdAccesoField;
            }
            set {
                if ((this.IdAccesoField.Equals(value) != true)) {
                    this.IdAccesoField = value;
                    this.RaisePropertyChanged("IdAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteBibliotecaElSaber.ServidorElSaber.UsuarioBinding IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoDeUsuario {
            get {
                return this.tipoDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDeUsuarioField, value) != true)) {
                    this.tipoDeUsuarioField = value;
                    this.RaisePropertyChanged("tipoDeUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocioBinding", Namespace="http://schemas.datacontract.org/2004/07/ElSaberServices.Contratos")]
    [System.SerializableAttribute()]
    public partial class SocioBinding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaDeInscripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroDeSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaDeInscripcion {
            get {
                return this.fechaDeInscripcionField;
            }
            set {
                if ((this.fechaDeInscripcionField.Equals(value) != true)) {
                    this.fechaDeInscripcionField = value;
                    this.RaisePropertyChanged("fechaDeInscripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroDeSocio {
            get {
                return this.numeroDeSocioField;
            }
            set {
                if ((this.numeroDeSocioField.Equals(value) != true)) {
                    this.numeroDeSocioField = value;
                    this.RaisePropertyChanged("numeroDeSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorElSaber.IUsuarioManejador")]
    public interface IUsuarioManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioManejador/RegistrarUsuarioAlaBaseDeDatos", ReplyAction="http://tempuri.org/IUsuarioManejador/RegistrarUsuarioAlaBaseDeDatosResponse")]
        int RegistrarUsuarioAlaBaseDeDatos(ClienteBibliotecaElSaber.ServidorElSaber.UsuarioBinding usuario, ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion, ClienteBibliotecaElSaber.ServidorElSaber.AccesoBinding acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioManejador/RegistrarUsuarioAlaBaseDeDatos", ReplyAction="http://tempuri.org/IUsuarioManejador/RegistrarUsuarioAlaBaseDeDatosResponse")]
        System.Threading.Tasks.Task<int> RegistrarUsuarioAlaBaseDeDatosAsync(ClienteBibliotecaElSaber.ServidorElSaber.UsuarioBinding usuario, ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion, ClienteBibliotecaElSaber.ServidorElSaber.AccesoBinding acceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioManejador/VerificarExistenciaDeUsuario", ReplyAction="http://tempuri.org/IUsuarioManejador/VerificarExistenciaDeUsuarioResponse")]
        int VerificarExistenciaDeUsuario(string correo, string telefonp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioManejador/VerificarExistenciaDeUsuario", ReplyAction="http://tempuri.org/IUsuarioManejador/VerificarExistenciaDeUsuarioResponse")]
        System.Threading.Tasks.Task<int> VerificarExistenciaDeUsuarioAsync(string correo, string telefonp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioManejadorChannel : ClienteBibliotecaElSaber.ServidorElSaber.IUsuarioManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioManejadorClient : System.ServiceModel.ClientBase<ClienteBibliotecaElSaber.ServidorElSaber.IUsuarioManejador>, ClienteBibliotecaElSaber.ServidorElSaber.IUsuarioManejador {
        
        public UsuarioManejadorClient() {
        }
        
        public UsuarioManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarUsuarioAlaBaseDeDatos(ClienteBibliotecaElSaber.ServidorElSaber.UsuarioBinding usuario, ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion, ClienteBibliotecaElSaber.ServidorElSaber.AccesoBinding acceso) {
            return base.Channel.RegistrarUsuarioAlaBaseDeDatos(usuario, direccion, acceso);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarUsuarioAlaBaseDeDatosAsync(ClienteBibliotecaElSaber.ServidorElSaber.UsuarioBinding usuario, ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion, ClienteBibliotecaElSaber.ServidorElSaber.AccesoBinding acceso) {
            return base.Channel.RegistrarUsuarioAlaBaseDeDatosAsync(usuario, direccion, acceso);
        }
        
        public int VerificarExistenciaDeUsuario(string correo, string telefonp) {
            return base.Channel.VerificarExistenciaDeUsuario(correo, telefonp);
        }
        
        public System.Threading.Tasks.Task<int> VerificarExistenciaDeUsuarioAsync(string correo, string telefonp) {
            return base.Channel.VerificarExistenciaDeUsuarioAsync(correo, telefonp);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorElSaber.IRestablecimientoCuentaManejador")]
    public interface IRestablecimientoCuentaManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestablecimientoCuentaManejador/CorreoDeRestablecimientoDeCon" +
            "trasenia", ReplyAction="http://tempuri.org/IRestablecimientoCuentaManejador/CorreoDeRestablecimientoDeCon" +
            "traseniaResponse")]
        int CorreoDeRestablecimientoDeContrasenia(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestablecimientoCuentaManejador/CorreoDeRestablecimientoDeCon" +
            "trasenia", ReplyAction="http://tempuri.org/IRestablecimientoCuentaManejador/CorreoDeRestablecimientoDeCon" +
            "traseniaResponse")]
        System.Threading.Tasks.Task<int> CorreoDeRestablecimientoDeContraseniaAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestablecimientoCuentaManejador/RestablecimientoDeContrasenia" +
            "", ReplyAction="http://tempuri.org/IRestablecimientoCuentaManejador/RestablecimientoDeContrasenia" +
            "Response")]
        int RestablecimientoDeContrasenia(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestablecimientoCuentaManejador/RestablecimientoDeContrasenia" +
            "", ReplyAction="http://tempuri.org/IRestablecimientoCuentaManejador/RestablecimientoDeContrasenia" +
            "Response")]
        System.Threading.Tasks.Task<int> RestablecimientoDeContraseniaAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestablecimientoCuentaManejador/VerificarCodigoDeVerificacion" +
            "", ReplyAction="http://tempuri.org/IRestablecimientoCuentaManejador/VerificarCodigoDeVerificacion" +
            "Response")]
        bool VerificarCodigoDeVerificacion(string correo, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestablecimientoCuentaManejador/VerificarCodigoDeVerificacion" +
            "", ReplyAction="http://tempuri.org/IRestablecimientoCuentaManejador/VerificarCodigoDeVerificacion" +
            "Response")]
        System.Threading.Tasks.Task<bool> VerificarCodigoDeVerificacionAsync(string correo, string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestablecimientoCuentaManejadorChannel : ClienteBibliotecaElSaber.ServidorElSaber.IRestablecimientoCuentaManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestablecimientoCuentaManejadorClient : System.ServiceModel.ClientBase<ClienteBibliotecaElSaber.ServidorElSaber.IRestablecimientoCuentaManejador>, ClienteBibliotecaElSaber.ServidorElSaber.IRestablecimientoCuentaManejador {
        
        public RestablecimientoCuentaManejadorClient() {
        }
        
        public RestablecimientoCuentaManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestablecimientoCuentaManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestablecimientoCuentaManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestablecimientoCuentaManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CorreoDeRestablecimientoDeContrasenia(string correo) {
            return base.Channel.CorreoDeRestablecimientoDeContrasenia(correo);
        }
        
        public System.Threading.Tasks.Task<int> CorreoDeRestablecimientoDeContraseniaAsync(string correo) {
            return base.Channel.CorreoDeRestablecimientoDeContraseniaAsync(correo);
        }
        
        public int RestablecimientoDeContrasenia(string correo) {
            return base.Channel.RestablecimientoDeContrasenia(correo);
        }
        
        public System.Threading.Tasks.Task<int> RestablecimientoDeContraseniaAsync(string correo) {
            return base.Channel.RestablecimientoDeContraseniaAsync(correo);
        }
        
        public bool VerificarCodigoDeVerificacion(string correo, string codigo) {
            return base.Channel.VerificarCodigoDeVerificacion(correo, codigo);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarCodigoDeVerificacionAsync(string correo, string codigo) {
            return base.Channel.VerificarCodigoDeVerificacionAsync(correo, codigo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorElSaber.IAccesoManejador")]
    public interface IAccesoManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesoManejador/VerificarCredenciales", ReplyAction="http://tempuri.org/IAccesoManejador/VerificarCredencialesResponse")]
        int VerificarCredenciales(string correo, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesoManejador/VerificarCredenciales", ReplyAction="http://tempuri.org/IAccesoManejador/VerificarCredencialesResponse")]
        System.Threading.Tasks.Task<int> VerificarCredencialesAsync(string correo, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesoManejador/VerificarCorreoExistente", ReplyAction="http://tempuri.org/IAccesoManejador/VerificarCorreoExistenteResponse")]
        int VerificarCorreoExistente(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesoManejador/VerificarCorreoExistente", ReplyAction="http://tempuri.org/IAccesoManejador/VerificarCorreoExistenteResponse")]
        System.Threading.Tasks.Task<int> VerificarCorreoExistenteAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesoManejador/ModificarContrasenia", ReplyAction="http://tempuri.org/IAccesoManejador/ModificarContraseniaResponse")]
        int ModificarContrasenia(string correo, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccesoManejador/ModificarContrasenia", ReplyAction="http://tempuri.org/IAccesoManejador/ModificarContraseniaResponse")]
        System.Threading.Tasks.Task<int> ModificarContraseniaAsync(string correo, string contrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccesoManejadorChannel : ClienteBibliotecaElSaber.ServidorElSaber.IAccesoManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccesoManejadorClient : System.ServiceModel.ClientBase<ClienteBibliotecaElSaber.ServidorElSaber.IAccesoManejador>, ClienteBibliotecaElSaber.ServidorElSaber.IAccesoManejador {
        
        public AccesoManejadorClient() {
        }
        
        public AccesoManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccesoManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccesoManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccesoManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int VerificarCredenciales(string correo, string telefono) {
            return base.Channel.VerificarCredenciales(correo, telefono);
        }
        
        public System.Threading.Tasks.Task<int> VerificarCredencialesAsync(string correo, string telefono) {
            return base.Channel.VerificarCredencialesAsync(correo, telefono);
        }
        
        public int VerificarCorreoExistente(string correo) {
            return base.Channel.VerificarCorreoExistente(correo);
        }
        
        public System.Threading.Tasks.Task<int> VerificarCorreoExistenteAsync(string correo) {
            return base.Channel.VerificarCorreoExistenteAsync(correo);
        }
        
        public int ModificarContrasenia(string correo, string contrasenia) {
            return base.Channel.ModificarContrasenia(correo, contrasenia);
        }
        
        public System.Threading.Tasks.Task<int> ModificarContraseniaAsync(string correo, string contrasenia) {
            return base.Channel.ModificarContraseniaAsync(correo, contrasenia);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorElSaber.IDireccionManejador")]
    public interface IDireccionManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccionManejador/RegistrarDireccion", ReplyAction="http://tempuri.org/IDireccionManejador/RegistrarDireccionResponse")]
        int RegistrarDireccion(ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDireccionManejador/RegistrarDireccion", ReplyAction="http://tempuri.org/IDireccionManejador/RegistrarDireccionResponse")]
        System.Threading.Tasks.Task<int> RegistrarDireccionAsync(ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDireccionManejadorChannel : ClienteBibliotecaElSaber.ServidorElSaber.IDireccionManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DireccionManejadorClient : System.ServiceModel.ClientBase<ClienteBibliotecaElSaber.ServidorElSaber.IDireccionManejador>, ClienteBibliotecaElSaber.ServidorElSaber.IDireccionManejador {
        
        public DireccionManejadorClient() {
        }
        
        public DireccionManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DireccionManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DireccionManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DireccionManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarDireccion(ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion) {
            return base.Channel.RegistrarDireccion(direccion);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarDireccionAsync(ClienteBibliotecaElSaber.ServidorElSaber.DireccionBinding direccion) {
            return base.Channel.RegistrarDireccionAsync(direccion);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorElSaber.ISocioManejador")]
    public interface ISocioManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/RegistrarSocioEnBaseDeDatos", ReplyAction="http://tempuri.org/ISocioManejador/RegistrarSocioEnBaseDeDatosResponse")]
        int RegistrarSocioEnBaseDeDatos(ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding socio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/RegistrarSocioEnBaseDeDatos", ReplyAction="http://tempuri.org/ISocioManejador/RegistrarSocioEnBaseDeDatosResponse")]
        System.Threading.Tasks.Task<int> RegistrarSocioEnBaseDeDatosAsync(ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding socio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/VerificarExistenciaDeSocioEnBaseDeDatos", ReplyAction="http://tempuri.org/ISocioManejador/VerificarExistenciaDeSocioEnBaseDeDatosRespons" +
            "e")]
        int VerificarExistenciaDeSocioEnBaseDeDatos(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/VerificarExistenciaDeSocioEnBaseDeDatos", ReplyAction="http://tempuri.org/ISocioManejador/VerificarExistenciaDeSocioEnBaseDeDatosRespons" +
            "e")]
        System.Threading.Tasks.Task<int> VerificarExistenciaDeSocioEnBaseDeDatosAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/ConsultarSociosPorNombre", ReplyAction="http://tempuri.org/ISocioManejador/ConsultarSociosPorNombreResponse")]
        ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding[] ConsultarSociosPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/ConsultarSociosPorNombre", ReplyAction="http://tempuri.org/ISocioManejador/ConsultarSociosPorNombreResponse")]
        System.Threading.Tasks.Task<ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding[]> ConsultarSociosPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/ConsultarSocioPorNumeroDeSocio", ReplyAction="http://tempuri.org/ISocioManejador/ConsultarSocioPorNumeroDeSocioResponse")]
        ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding ConsultarSocioPorNumeroDeSocio(int numeroDeSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioManejador/ConsultarSocioPorNumeroDeSocio", ReplyAction="http://tempuri.org/ISocioManejador/ConsultarSocioPorNumeroDeSocioResponse")]
        System.Threading.Tasks.Task<ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding> ConsultarSocioPorNumeroDeSocioAsync(int numeroDeSocio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocioManejadorChannel : ClienteBibliotecaElSaber.ServidorElSaber.ISocioManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocioManejadorClient : System.ServiceModel.ClientBase<ClienteBibliotecaElSaber.ServidorElSaber.ISocioManejador>, ClienteBibliotecaElSaber.ServidorElSaber.ISocioManejador {
        
        public SocioManejadorClient() {
        }
        
        public SocioManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocioManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocioManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocioManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarSocioEnBaseDeDatos(ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding socio) {
            return base.Channel.RegistrarSocioEnBaseDeDatos(socio);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarSocioEnBaseDeDatosAsync(ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding socio) {
            return base.Channel.RegistrarSocioEnBaseDeDatosAsync(socio);
        }
        
        public int VerificarExistenciaDeSocioEnBaseDeDatos(string telefono) {
            return base.Channel.VerificarExistenciaDeSocioEnBaseDeDatos(telefono);
        }
        
        public System.Threading.Tasks.Task<int> VerificarExistenciaDeSocioEnBaseDeDatosAsync(string telefono) {
            return base.Channel.VerificarExistenciaDeSocioEnBaseDeDatosAsync(telefono);
        }
        
        public ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding[] ConsultarSociosPorNombre(string nombre) {
            return base.Channel.ConsultarSociosPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding[]> ConsultarSociosPorNombreAsync(string nombre) {
            return base.Channel.ConsultarSociosPorNombreAsync(nombre);
        }
        
        public ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding ConsultarSocioPorNumeroDeSocio(int numeroDeSocio) {
            return base.Channel.ConsultarSocioPorNumeroDeSocio(numeroDeSocio);
        }
        
        public System.Threading.Tasks.Task<ClienteBibliotecaElSaber.ServidorElSaber.SocioBinding> ConsultarSocioPorNumeroDeSocioAsync(int numeroDeSocio) {
            return base.Channel.ConsultarSocioPorNumeroDeSocioAsync(numeroDeSocio);
        }
    }
}
